plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish'
}
version = project.mod_version
group = project.maven_group
base { archivesName = 'icys-better-horses' }
loom {
    mixin { defaultRefmapName = 'icys-better-horses-refmap.json' }
}
repositories {
    maven { url = 'https://api.modrinth.com/maven'; content { includeGroup 'maven.modrinth' } }
    maven { url = 'https://maven.terraformersmc.com/releases/'; content { includeGroup 'com.terraformersmc' } }
    maven { url = 'https://maven.shedaniel.me/'; content { includeGroup 'me.shedaniel.cloth' } }
}
dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    modImplementation "maven.modrinth:geckolib:${project.geckolib_version_id}"
    modImplementation "maven.modrinth:modonomicon:${project.modonomicon_version_id}"
    modLocalRuntime "me.zeroeightsix:fiber:0.23.0-2"
    runtimeOnly "org.commonmark:commonmark:0.22.0"
    runtimeOnly "org.commonmark:commonmark-ext-gfm-strikethrough:0.22.0"
    runtimeOnly "org.commonmark:commonmark-ext-ins:0.22.0"
    modImplementation "com.terraformersmc:modmenu:${project.modmenu_version}"
    modImplementation("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}") { exclude group: 'net.fabricmc.fabric-api' }
    modCompileOnly "maven.modrinth:galosphere:jviVa3qz"
    modLocalRuntime "maven.modrinth:galosphere:jviVa3qz"
    modLocalRuntime "maven.modrinth:tooltip-overhaul:m0AJxY9X"
    modLocalRuntime "maven.modrinth:vics-point-blank:7FaixPLu"
    modLocalRuntime "maven.modrinth:architectury-api:Pzc2FP5K"
    modLocalRuntime "maven.modrinth:epic-knights-shields-armor-and-weapons:dLYqLDl7"
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.0'
}
processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand version: project.version }
    exclude '**/*.bbmodel'
}
java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}
tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
    options.compilerArgs.addAll(['-Xmaxerrs', '300'])
}
test { useJUnitPlatform() }
jar { from('LICENSE') { rename { "${it}_icys-better-horses" } } }
