org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=C:/Program Files/Java/jdk-21.0.10
org.gradle.parallel=true
org.gradle.configuration-cache=false
minecraft_version=1.21.1
loader_version=0.18.4
loom_version=1.10.5
mod_version=2.1.0
maven_group=icy.betterhorses.net
fabric_api_version=0.116.15+1.21.1
geckolib_version=4.7.5.1
geckolib_version_id=PEvrTvgj
modonomicon_version=1.120.4
modonomicon_version_id=Qa8mMyKW
modmenu_version=11.0.3
cloth_config_version=15.0.140
